[package]
name = "santa"
version = "0.1.0"
edition = "2021"
authors = ["Tyler Butler <tyler@tylerbutler.com>"]
license = "MIT"
description = "a tool that manages packages across different platforms"
repository = "https://github.com/tylerbutler/santa"
readme = "README.md"
rust-version = "1.70.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4", features = ["color", "derive", "cargo", "wrap_help"] }
clap_complete = "4.4"
colored = "2"
config = "0.14"
dialoguer = "0.11.0"
directories = "4.0"
log = "0.4.14"
serde = { version = "1.0.130", features = ["derive"] }
serde-enum-str = "0.2.4"
serde_yaml = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tabular = "0.2.0"
subprocess = "0.2.8"
termcolor = "1.1.*"

[[bin]]
name = "santa"
path = "src/main.rs"
