name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - command: release
            concurrency-group: release-plz-release
          - command: release-pr
            concurrency-group: release-plz-${{ github.ref }}

    concurrency:
      group: ${{ matrix.concurrency-group }}
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # ratchet:actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ./.github/actions/setup-rust

      - name: Run release-plz
        uses: release-plz/action@d529f731ae3e89610ada96eda34e5c6ba3b12214 # ratchet:release-plz/action@v0.5
        with:
          command: ${{ matrix.command }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
